#vue js deployment using github actions
name: Vue Js CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    # runs-on: ubuntu-latest
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x, 16.x, 17.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/checkout@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test:unit
      - name: lint
        run: npm run lint
      - name: Build
        run: npm run build
      # - name: preview
        # run: npm run preview
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch